spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy
    username: juca
    password: perigoso0987
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
